### ISSUE TITLE
HTTParty appears twice in gemspec

### ISSUE THREAD

**Issue by sgerrand** [aaronrussell/postcodeanywhere_banking#1]
The `httparty` gem [appears twice in the gemspec for v0.0.2](https://github.com/aaronrussell/postcodeanywhere_banking/blob/v0.0.2/postcodeanywhere_banking.gemspec#L48-73), most likely because it's declared once in the Gemfile and then picked up again by `Jeweler`.

**Comment by sgerrand** [comment]
@aaronrussell: Would you please review this change. :wave:

**Comment by aaronrussell-x** [comment]
@sgerrand I've merged the PR, but I don't even have a working copy of this any more as I only built it for one project a few years back.

If you're actively using this, would you like me to add you as a collaborator and make you an owner of the rubygem so you can push any new versions?

**Comment by sgerrand** [comment]
> @sgerrand I've merged the PR, but I don't even have a working copy of this any more as I only built it for one project a few years back.
> 
> If you're actively using this, would you like me to add you as a collaborator and make you an owner of the rubygem so you can push any new versions?

I'd be happy to. 👍

**Comment by sgerrand** [comment]
> > If you're actively using this, would you like me to add you as a collaborator and make you an owner of the rubygem so you can push any new versions?
> 
> I'd be happy to. 👍

@aaronrussell: :wave:

**Comment by aaronrussell-x** [comment]
My apologies. Can you give me an email address so I can add you to the rubygems project?
